name: Blank issue
description: Create a new issue from scratch
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing an issue to our project!
  - type: markdown
    attributes:
      value: |
        If you are reporting a bug, please use our bug report template. If you are requesting a feature, please use our feature request template.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true